ko_fi: koeqaife
custom: [
  'https://www.donationalerts.com/r/koeqaife',
  'https://etherscan.io/address/0xC6eaFAB219EaF1F050eF93Abe48Bfdd84D325Ccc',
  'https://tronscan.org/#/address/TB4jWa9GT6gXWueNEMzWfpoLaytnuWon2W'
]