hl.on("hyprland.start", function ()
    hl.exec_cmd("/usr/lib/hypryou/assets/hyprland/scripts/xdg.sh")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hyprsunset")
end)
