$mainMod = SUPER

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = , XF86MonBrightnessUp, exec, brightnessctl -q s +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl -q s 10%-
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Use this if hypryou isn't running
bind = $mainMod, K, exec, bash -c 'term="${XDG_UTILS_TERMINAL:-}"; \
  if [ -n "$term" ] && command -v "$term" >/dev/null 2>&1; then exec "$term"; \
  else for t in kitty alacritty foot wezterm xterm; do \
    command -v "$t" >/dev/null 2>&1 && exec "$t"; done; \
  fi'
