# ######## Window rules ########
windowrulev2 = tile, class:^(Microsoft-edge)$
windowrulev2 = tile, class:^(Brave-browser)$
windowrulev2 = tile, class:^(Chromium)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(blueberry.py)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(qalculate-gtk)$
windowrulev2 = float, class:^(steam)$
windowrulev2 = float, class:^(com.koeqaife.hypryou)$
windowrulev2 = stayfocused, title:^()$, class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$, class:^(steam)$
windowrulev2 = float, title:^(Volume Control)(.*)$

# Xwaylandvideobridge (if installed)
windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrulev2 = noanim, class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrulev2 = noblur, class:^(xwaylandvideobridge)$

# Dialogs
windowrulev2 = float, title:^(Open File)(.*)$
windowrulev2 = float, title:^(Select a File)(.*)$
windowrulev2 = float, title:^(Choose wallpaper)(.*)$
windowrulev2 = float, title:^(Open Folder)(.*)$
windowrulev2 = float, title:^(Save As)(.*)$
windowrulev2 = float, title:^(Library)(.*)$
windowrulev2 = float, title:^(File Upload)(.*)$

# Tearing
windowrulev2 = immediate, class:.*\.exe
windowrulev2 = immediate, class:(steam_app)455

# ######## Layer rules ########
# layerrulev2 = xray 1, .*
# layerrulev2 = noanim, .*
layerrulev2 = noanim, selection
layerrulev2 = noanim, popup.*
layerrulev2 = noanim, hyprpicker
layerrulev2 = noanim, noanim
layerrulev2 = noanim, wallpapers
