# ######## Window rules ########
windowrule = match:class ^(Microsoft-edge)$, tile on
windowrule = match:class ^(Brave-browser)$, tile on
windowrule = match:class ^(Chromium)$, tile on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueberry.py)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(qalculate-gtk)$, float on
windowrule = match:class ^(steam)$, float on
windowrule = match:class ^(com.koeqaife.hypryou)$, float on
windowrule = match:title ^(Volume Control)(.*)$, float on

# Xwaylandvideobridge (if installed)
windowrule = match:class ^(xwaylandvideobridge)$, opacity 0.0 override
windowrule = match:class ^(xwaylandvideobridge)$, no_anim on
windowrule = match:class ^(xwaylandvideobridge)$, no_initial_focus on
windowrule = match:class ^(xwaylandvideobridge)$, max_size 1 1
windowrule = match:class ^(xwaylandvideobridge)$, no_blur on

# Dialogs
windowrule = match:title ^(Open File)(.*)$, float on
windowrule = match:title ^(Select a File)(.*)$, float on
windowrule = match:title ^(Choose wallpaper)(.*)$, float on
windowrule = match:title ^(Open Folder)(.*)$, float on
windowrule = match:title ^(Save As)(.*)$, float on
windowrule = match:title ^(Library)(.*)$, float on
windowrule = match:title ^(File Upload)(.*)$, float on

# Tearing
windowrule = match:class .*\.exe, immediate on
windowrule = match:class (steam_app)455, immediate on

# ######## Layer rules ########
# layerrule = xray 1, .*
# layerrule = noanim, .*
layerrule = match:namespace selection, no_anim on
layerrule = match:namespace popup.*, no_anim on
layerrule = match:namespace hyprpicker, no_anim on
layerrule = match:namespace noanim, no_anim on
layerrule = match:namespace wallpapers, no_anim on
