$mainMod = SUPER

bind = $mainMod, 1, exec, hypryouctl change_workspace 1
bind = $mainMod, 2, exec, hypryouctl change_workspace 2
bind = $mainMod, 3, exec, hypryouctl change_workspace 3
bind = $mainMod, 4, exec, hypryouctl change_workspace 4
bind = $mainMod, 5, exec, hypryouctl change_workspace 5
bind = $mainMod, 6, exec, hypryouctl change_workspace 6
bind = $mainMod, 7, exec, hypryouctl change_workspace 7
bind = $mainMod, 8, exec, hypryouctl change_workspace 8
bind = $mainMod, 9, exec, hypryouctl change_workspace 9
bind = $mainMod, 0, exec, hypryouctl change_workspace 10
bind = $mainMod SHIFT, 1, exec, hypryouctl move_window 1
bind = $mainMod SHIFT, 2, exec, hypryouctl move_window 2
bind = $mainMod SHIFT, 3, exec, hypryouctl move_window 3
bind = $mainMod SHIFT, 4, exec, hypryouctl move_window 4
bind = $mainMod SHIFT, 5, exec, hypryouctl move_window 5
bind = $mainMod SHIFT, 6, exec, hypryouctl move_window 6
bind = $mainMod SHIFT, 7, exec, hypryouctl move_window 7
bind = $mainMod SHIFT, 8, exec, hypryouctl move_window 8
bind = $mainMod SHIFT, 9, exec, hypryouctl move_window 9
bind = $mainMod SHIFT, 0, exec, hypryouctl move_window 10
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod CTRL, down, workspace, empty

bind = , XF86MonBrightnessUp, exec, brightnessctl -q s +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl -q s 10%-
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Use this if hypryou isn't running
bind = $mainMod, K, exec, bash -c 'term="${XDG_UTILS_TERMINAL:-}"; \
  if [ -n "$term" ] && command -v "$term" >/dev/null 2>&1; then exec "$term"; \
  else for t in kitty alacritty foot wezterm xterm; do \
    command -v "$t" >/dev/null 2>&1 && exec "$t"; done; \
  fi'

bind = $mainMod, P, submap, passthru
submap = passthru
bind = SUPER, Escape, submap, reset
submap = reset